<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Nimble.UI</AssemblyName>
		<TargetFramework>net8.0</TargetFramework>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Nimble.Core\Nimble.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="src\Component\" />
	  <Folder Include="src\Controller\" />
	  <Folder Include="src\View\" />
	</ItemGroup>
</Project>