<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>Nimble.Prototype</AssemblyName>
		<TargetFramework>net8.0</TargetFramework>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Nimble.Core\Nimble.Core.csproj" />
	  <ProjectReference Include="..\Nimble.UI\Nimble.UI.csproj" />
	</ItemGroup>
</Project>